# Generated by Django 4.2.4 on 2024-02-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default='Unnamed Flight', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_range',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
