# Generated by Django 4.2.4 on 2024-02-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_name_flight_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
